version: '3.9'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - db
    container_name: web_container

  db:
    image: mysql:8.0
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
